--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GamerMJay/EasySkin
build-by-default: true
branches:
- main
projects:
  EasySkin:
    path: ""
    icon: "icon.png"
    libs:
      - src: HimbeersaftLP/LibSkin/LibSkin
      - src: https://poggit.pmmp.io/ci/supercrafter333/FormAPI/libFormAPI
        version: ^2.1.0
...
